新規スタンプ作成のお知らせ投稿の スタンプに .ex-large を追加
traPtitech/traq-system-bot pull request #6
Opened 2024-05-17 05:38 UTC by Kaki256

https://q.trap.jp/messages/286b9527-d860-4519-a1e3-b6ab6fcd241d

2024-05-17 07:52 UTC, alter334 commented
LGTMです
(traQ初コードレビューであるかも...)

2024-05-22 01:50 UTC, alter334 requested changes
レビューの表示もれすみません...

2024-05-22 01:50 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
```suggestion
		if err := sendMessage(systemMessageChannelID, fmt.Sprintf(":%s.ex-large:\n\n%s が `:%s:` を作成しました", req.Name, createUserMention(req.Creator), req.Name)); err != nil {
```

takeno_hitoさんの実装方式です
自分はこの方式で行きたいと思っていますがどうでしょうか

2024-05-22 01:50 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
@Kaki256

2024-05-22 01:50 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
```suggestion
		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s が`:%s:`を作成しました。\n :%s.ex-large:", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
```

https://q.trap.jp/messages/d8b6fa43-6234-4e81-89c9-bcc09cd45bcc

この投稿に示したバージョンです
どうでしょうか

2024-05-22 01:50 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
@Kaki256

2024-05-22 02:06 UTC, Kaki256 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
恐らく takeno_hito さんのやつをほとんどそのまま貼ってくれてる気がするんですが、スタンプであることは明示したほうが良いかも + 半角と全角の間にスペースを入れたほうが良いかも です (何かと干渉するわけでもないですが、一応元々の投稿文を変えるほどの意味はないかな と考えています)

```suggestion
		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` を作成しました\n:%s.ex-large:", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
```

2024-05-22 02:13 UTC, Kaki256 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
@alter334

2024-05-22 06:15 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
ありがとうございます
そのようにして大丈夫です お願いします

2024-05-22 06:16 UTC, alter334 commented on bot.go
> +		if err := sendMessage(systemMessageChannelID, fmt.Sprintf("%s がスタンプ `:%s:` :%s.ex-large: を作成しました", createUserMention(req.Creator), req.Name, req.Name)); err != nil {
@Kaki256

2024-05-22 07:09 UTC, Kaki256 commented
@alter334 レビューお願いします🙇

2024-05-27 06:13 UTC, alter334 approved these changes
レビュー遅くなりすみません
文章的な違和感も少なそうなのでこちらで通そうかなと思います

2024-06-17 15:22 UTC, merged